### ISSUE TITLE
IRM-10-5 (2A DC Meanwell PSU) is not compatible with PCB

### ISSUE THREAD

**Issue by glbyers** [Retro-Commodore/C64-PSU#1]
Just an FYI to anyone else that is interested in this project. The Meanwell IRM-10-5 PSU as linked in the itemlist is not compatible with the v1.2 board. AC/N and AC/L traces and vias would need adjustment to suit.

Thanks for the project. Simple design for a nice PSU!

**Comment by tomse** [comment]
thanks for the info. I've "removed" the IRM-10-5 from the documentation.

I hope you'll find the PSU useful :-)
