### ISSUE TITLE
Texts on bottom layer are not mirrored

### ISSUE THREAD

**Issue by fabbrimichele** [Retro-Commodore/C64-PSU#2]
Hello,

thank you for sharing this project!
I just wanted to report a small issue related to the text in the bottom layer of the circuit board.
I was told by circuit board factory JLCPCB that the text is not mirrored and it should.
See the attached image:
![c64-psu-text](https://user-images.githubusercontent.com/48403836/66040701-6f40bc00-e518-11e9-9524-1c1de9d74ccd.png)

**Comment by tomse** [comment]
thanks for the report. if you have patience and can wait till the weekend, I can check my v1.4 pcb's
they should be mirrored, the v1.4 boards are produced from jlcpcb and there were no problems.

did you upload the finished gerber files to them?
https://github.com/Retro-Commodore/C64-PSU/blob/master/Hardware/Eagle/Gerber_C64%20PSU_v1.4_2019-06-28.zip

**Comment by fabbrimichele** [comment]
Hello tomse,

yes I uploaded the file you mentioned.
I'm wondering if they are mistaking, anyhow I asked them to mirror the text if there is no additional cost.

I'll let you know as soon as I receive the printed circuit board.

Thanks and regards,
Michele

**Comment by tomse** [comment]
I just noticed the silkscreen for the fuse says 200mA, but you should get T 500mA instead. the 5v DC module pulls a lot of startup current.  
I'll see to fix this for v1.5

**Comment by fabbrimichele** [comment]
OK, thanks for the advice!

**Comment by fabbrimichele** [comment]
Hello,

I would a question about the fuse, should it be quick blow or time lag?
I found the following ones in the e-commerce site suggested in the documentation:
* quick blow https://www.tme.eu/de/en/details/0217.500hxp/fuses-5x20mm-fast/littelfuse
* time lage: https://www.tme.eu/de/en/details/0218.500hxp/fuses-5x20mm-time-lag/littelfuse

Thanks in advance.

Cheers,
Michele

**Comment by tomse** [comment]
time lag / slow blow is prefered here.
cheers

**Comment by fabbrimichele** [comment]
Thanks for the answer! I'm going to order the components and build the power supply.

**Comment by fabbrimichele** [comment]
Hello,

I finished the PSU. Keeping the cable between the c64 and PSU short 1.10 m,
I managed to have 4.88 volt at U8 on the board.

Thank you very much for your project.

Cheers,
Michele

**Comment by tomse** [comment]
You're welcome.. as a reference, the original C64 psu gives around 4.6v at the farthest IC on the board, can't remember which IC it is, though lower left corner :-)

**Comment by fabbrimichele** [comment]
U8 is on the left side. That means the PSU is great. Thanks again!
